fix: add get latest release

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -33,6 +33,18 @@ jobs:
           changelog-generator-opt: emojis=true
           allow-initial-development-versions: true
 
+      - name: Get latest release
+        if: steps.go-semantic-release.outputs.version != ''
+        id: get_latest_release
+        run: |
+          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
+          upload_url=$(echo "$response" | jq -r '.upload_url')
+          if [ "$upload_url" = "null" ]; then
+            echo "::error::Upload URL is null for the latest release."
+            exit 1
+          fi
+          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV
+
       - name: Download build artifact
         if: steps.go-semantic-release.outputs.version != ''
         uses: actions/download-artifact@v4
